global using System;
global using System.Buffers;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Management.Automation;
global using System.Management.Automation.Language;
global using System.Net.Http;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Markdig;
global using Markdig.Extensions;
global using Markdig.Extensions.AutoLinks;
global using Markdig.Extensions.TaskLists;
global using Markdig.Helpers;
global using Markdig.Syntax;
global using Markdig.Syntax.Inlines;
global using Microsoft.CSharp.RuntimeBinder;
global using PSTextMate;
global using PSTextMate.Core;
global using PSTextMate.Sixel;
global using PSTextMate.Terminal;
global using PSTextMate.Utilities;
global using SixLabors.ImageSharp.PixelFormats;
global using SixLabors.ImageSharp.Processing;
global using SixLabors.ImageSharp.Processing.Processors.Quantization;
global using SixLabors.ImageSharp.Processing.Processors.Transforms;
global using Spectre.Console;
global using Spectre.Console.Rendering;
global using TextMateSharp.Grammars;
global using TextMateSharp.Registry;
global using TextMateSharp.Themes;
global using Color = Spectre.Console.Color;
global using PSHostUserInterface = System.Management.Automation.Host.PSHostUserInterface;
global using SixColor = SixLabors.ImageSharp.Color;
global using SixImage = SixLabors.ImageSharp.Image;
global using TableColumnAlign = Markdig.Extensions.Tables.TableColumnAlign;
